apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  creationTimestamp: "2020-04-15T09:19:03Z"
  finalizers:
  - 99-worker-27dee4fd-f902-48da-83da-bd9a103da81c-kubelet
  generation: 3
  name: worker-kubeconfig
  resourceVersion: "12125820"
  selfLink: /apis/machineconfiguration.openshift.io/v1/kubeletconfigs/worker-kubeconfig
  uid: 7a4cdbb9-f197-4696-9f73-26962beddf1b
spec:
  kubeletConfig:
    evictionHard:
      imagefs.available: 10%
      imagefs.inodesFree: 5%
      memory.available: 200Mi
      nodefs.available: 25%
      nodefs.inodesFree: 4%
    evictionPressureTransitionPeriod: 0s
    evictionSoft:
      imagefs.available: 15%
      imagefs.inodesFree: 10%
      memory.available: 500Mi
      nodefs.available: 25%
      nodefs.inodesFree: 5%
    evictionSoftGracePeriod:
      imagefs.available: 1m30s
      imagefs.inodesFree: 1m30s
      memory.available: 1m30s
      nodefs.available: 1m30s
      nodefs.inodesFree: 1m30s
    imageGCHighThresholdPercent: 80
    imageGCLowThresholdPercent: 75
    imageMinimumGCAge: 5m
  machineConfigPoolSelector:
    matchLabels:
      gc-enabled: "true"
status:
  conditions:
  - lastTransitionTime: "2020-04-15T09:19:03Z"
    message: 'Error: could not find any MachineConfigPool set for KubeletConfig'
    status: "False"
    type: Failure
  - lastTransitionTime: "2020-04-15T09:25:30Z"
    message: Success
    status: "True"
    type: Success
  - lastTransitionTime: "2020-04-15T09:39:47Z"
    message: Success
    status: "True"
    type: Success
